version: '3.8'
services:
  db:
    image: postgres:latest
    volumes:
    - db-data:/var/lib/postgresql/data
    ports:
    - 5432:5432
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_DB: mash
      POSTGRES_USER: mash

  lfs:
    image: jasonwhite0/rudolfs:0.3.5
    ports:
      - 8888:8888
    environment:
      RUDOLFS_KEY: "0bce26498d4f9765c6702d3b6cc43dca2daa2a4e9ac003373512d4f78828f183"
    command:
      - --host=0.0.0.0:8888
      - local
      - --path=/lfs
    volumes:
      - lfs-data:/lfs

  ssh:
    build: ./mutagen-ssh
    ports:
      - 2222:2222
      - 6061:6060
    command:
      - mutagen-ssh
      - --ssh-listen-addr=0.0.0.0:2222
      - --ssh-key-path=/keys/id_ed25519
    volumes:
      - ./api/tmp/repos:/repos
      - ./mutagen-ssh/cmd/mutagen-ssh/keys:/keys

volumes:
  db-data:
    driver: local
  lfs-data:
    driver: local
