steps:
  - label: ":docker: :golang: Run unit tests"
    commands:
      - "./download && cd ./tmp_output"
      - "docker-compose -f ci/docker-compose.yaml -f ci/unit/docker-compose.yaml up --build --exit-code-from runner"

  - label: ":docker: :yarn: Lint and test"
    commands:
      - "./download && cd ./tmp_output"
      - "export UID && export GID=$(id -g $(whoami)) && docker-compose -f ci/docker-compose.web.yaml up --build --exit-code-from web-runner"
