version: "3.9"
services:
  go:
    build:
      context: ..
      dockerfile: ci/Dockerfile
    volumes:
      - ..:/sturdy
      - go-modules:/go/pkg/mod
    working_dir: /sturdy

volumes:
  go-modules:
