version: '3.8'
services:
  sturdy:
    image: getsturdy/server:latest
    pull_policy: always
    volumes:
      - sturdy-data:/var/data
    ports:
      # Listen on port 80 and forward traffic to Sturdy on port 7000
      - "80:7000"

volumes:
  sturdy-data:
    driver: local
